### ISSUE TITLE
Add CI pipeline

### ISSUE THREAD

**Issue by LGro** [erkannt/wissenschaftsbefreiungsfront#1]
To make sure the tests are passing and the setup details are up-to-date, add a CI pipeline, e.g. with [buildkite](https://buildkite.com) or [GitHub Actions](https://github.com/erkannt/wissenschaftsbefreiungsfront/actions).

**Comment by erkannt** [comment]
Closed by c30668601a6f87cb086eb3cd19de7d7a47bc5c5e and 9929cd0

Should have remembered to use the issue # in the commit... :doh:
