### ISSUE TITLE
Add coverage report

### ISSUE THREAD

**Issue by LGro** [erkannt/wissenschaftsbefreiungsfront#2]
@erkannt, would you be so kind to register at https://codecov.io/ and enable the coverage analysis for this repo so we can add a badge to the README and potentially use this as a source of information for future PR workflows?
Alternatively, we can also move the repo to a new GitHub org that we are both admins of so I can do it myself.

**Comment by erkannt** [comment]
`CODECOV_TOKEN` is now available as a github secret. I suggest we move the repo if this thing has legs and gets a better name ^^
